### PR TITLE
Improve travis configuration

### PR DESCRIPTION
**Pull request by abinoam**
~Work in progress~

This PR fixes the Codeclimate related error.
But the travis builds are stopping later on the run.
I have tried to dig a little onto this thing but, I think I'm not up to handle the complexities of installing gnuplot dependencies on travis.
So, here's the PR that fixes at least one small part of the issue.

### CODE REVIEW

**Comment by abinoam** [comment]
CC: @dilcom

**Comment by abinoam** [comment]
Basically, Codeclimate has changed its api for SimpleCov:
https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.md#v100-2016-11-03

See the instructions that I have applied at this PR:
* https://docs.codeclimate.com/docs/travis-ci-ruby-test-coverage
* https://docs.codeclimate.com/docs/test-coverage-ruby

**Comment by dilcom** [comment]
Hi @abinoam ,

I also tried to fix Travis job in my PR but your changes look better :). So I'm merging this.
Lets see if I'll manage to cope with jruby/mac builds.

Thanks a lot!

**Comment by abinoam** [comment]
Thanks for merging!
Thanks for GnuplotRB!

**Pull request merged**
